### ISSUE TITLE
start progarm fail

### ISSUE THREAD

**Issue by vaecebyZ** [unjs/get-port-please#97]
### Environment

get-port-please：3.1.2
os: Windwos11 23H2 22631.3593
node: 20.12.2
pnpm: 9.1.1
vite: 5.2.7

### Reproduction

just fixed. now it works.

### Describe the bug

today i start my progarm.  up faild by "Unable to find a random port on any host" , then I find function '[checkPort()](https://github.com/unjs/get-port-please/blob/3c17e48c71021e79b9a12e310486d26c94f58e26/src/get-port.ts#L124)' return false.
in function the [_getLocalHosts()](https://github.com/unjs/get-port-please/blob/3c17e48c71021e79b9a12e310486d26c94f58e26/src/get-port.ts#L154) get array host but host[0] = undefined, so  [_tryPort()](https://github.com/unjs/get-port-please/blob/3c17e48c71021e79b9a12e310486d26c94f58e26/src/_internal.ts#L33) will get one false , then the false value will be return and get checkPort() fail .

I commented out this line.now its work (temporarily)🤣🤣🤣
![image](https://github.com/unjs/get-port-please/assets/45579121/ae4945b7-dc43-46cf-bf29-a33d7555cbf8)

thanks.

### Additional context

this is console value:
`  if (!host) {
    host = _getLocalHosts([void 0, "0.0.0.0"]);
    console.log(host)
  }
//[
  undefined,
  '0.0.0.0',
  '192.168.0.5',
  '192.168.56.1',
  '192.168.150.2',
  '169.254.158.97',
  '192.168.79.1',
  '10.144.103.31',
  '192.168.60.1'
]

=====================

  for (const _host of host) {
    const _port = await _tryPort(port, _host);
    console.log("_port",_port)
    ....
}

//_port 3070
_port 3070
_port 3070
_port 3070
_port 3070
_port false
`

### Logs

```sh
error when starting dev server:
GetPortError: Unable to find a random port on any host
    at getRandomPort (file:///D:/code/fcadmin/node_modules/.pnpm/get-port-please@3.1.2/node_modules/get-port-please/dist/index.mjs:337:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async detectPort (file:///D:/code/fcadmin/node_modules/.pnpm/unplugin-turbo-console@1.8.6_esbuild@0.20.2_rollup@4.17.2_vite@5.2.11_@types+node@20.12.12_sa_ippzb4y57jtfn5cquesa6lt3mq/node_modules/unplugin-turbo-console/dist/chunk-CSBEKKJ2.js:554:22)
    at async configureServer (file:///D:/code/fcadmin/node_modules/.pnpm/unplugin-turbo-console@1.8.6_esbuild@0.20.2_rollup@4.17.2_vite@5.2.11_@types+node@20.12.12_sa_ippzb4y57jtfn5cquesa6lt3mq/node_modules/unplugin-turbo-console/dist/chunk-CSBEKKJ2.js:582:11)
    at async _createServer (file:///D:/code/fcadmin/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.12_sass@1.77.2_terser@5.31.0/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:65014:24)
    at async CAC.<anonymous> (file:///D:/code/fcadmin/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.12_sass@1.77.2_terser@5.31.0/node_modules/vite/dist/node/cli.js:762:24)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by pi0** [comment]
Hi @vaecebyZ thanks for the investigation. The `undefined` host trial is to check the operating system's _default_ host (which is not predictable easily). 

If you try `_tryPort(0, undefined)` on your machine would it return false?

**Comment by vaecebyZ** [comment]
> Hi @vaecebyZ thanks for the investigation. The `undefined` host trial is to check the operating system's _default_ host (which is not predictable easily).
> 
> If you try `_tryPort(0, undefined)` on your machine would it return false?

I try `_tryPort(0, undefined)` it not return false,but[ `for of  host`](https://github.com/unjs/get-port-please/blob/3c17e48c71021e79b9a12e310486d26c94f58e26/src/get-port.ts#L159) one of them returns false
![image](https://github.com/unjs/get-port-please/assets/45579121/41df5799-ffa8-41f7-a358-0959900a4163)
